In [4]:
import pandas as pd

In [5]:
df1=pd.DataFrame({'name': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Vikas',
             'Neha', 'Rohit', 'Pooja', 'Arjun', 'Kavya'],
    'age': [22, 25, 28, 21, 30, 24, 27, 23, 26, 29],
    'city': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur',
             'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Jaipur']
                  })

In [6]:
df1

    name  age       city
0  Rahul   22      Delhi
1  Priya   25     Mumbai
2   Amit   28       Pune
3  Sneha   21      Delhi
4  Vikas   30     Jaipur
5   Neha   24     Mumbai
6  Rohit   27  Hyderabad
7  Pooja   23       Pune
8  Arjun   26      Delhi
9  Kavya   29     Jaipur

In [7]:
df1.where(df1["age"] >= 25)

    name   age       city
0    NaN   NaN        NaN
1  Priya  25.0     Mumbai
2   Amit  28.0       Pune
3    NaN   NaN        NaN
4  Vikas  30.0     Jaipur
5    NaN   NaN        NaN
6  Rohit  27.0  Hyderabad
7    NaN   NaN        NaN
8  Arjun  26.0      Delhi
9  Kavya  29.0     Jaipur

In [8]:
df1.shape

(10, 3)

In [9]:
df1.to_csv("data/data.csv", index=False)

In [ ]:
df1